//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopping
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductThumb
    {
        public long ProductThumbId { get; set; }
        public int ProductId { get; set; }
        public int UserId { get; set; }
        public bool Up { get; set; }
    
        public virtual UserLogin UserLogin { get; set; }
        public virtual Product Product { get; set; }
    }
}
